### ISSUE TITLE
Dosen't work

### ISSUE THREAD

**Issue by mahlu** [jeanmatthieud/color-thief-jimp#1]
C:\Users\Mahlu\Desktop\example2\node_modules\color-thief-jimp\src\color-thief.js:71
    var pixels     = imageData.data;
                              ^

TypeError: Cannot read property 'data' of undefined
    at ColorThief.getPalette (C:\Users\Mahlu\Desktop\example2\node_modules\color-thief-jimp\src\color-thief.js:71:31)
    at ColorThief.getPaletteHex (C:\Users\Mahlu\Desktop\example2\node_modules\color-thief-jimp\src\color-thief.js:138:24)
    at ColorThief.getColorHex (C:\Users\Mahlu\Desktop\example2\node_modules\color-thief-jimp\src\color-thief.js:115:30)
    at C:\Users\Mahlu\Desktop\example2\api\scrapers\news\VOGUE.Test.ONE.js:145:48
    at C:\Users\Mahlu\Desktop\example2\node_modules\async\lib\async.js:718:13
    at iterate (C:\Users\Mahlu\Desktop\example2\node_modules\async\lib\async.js:262:13)
    at C:\Users\Mahlu\Desktop\example2\node_modules\async\lib\async.js:274:29
    at C:\Users\Mahlu\Desktop\example2\node_modules\async\lib\async.js:44:16
    at C:\Users\Mahlu\Desktop\example2\node_modules\async\lib\async.js:723:17
    at C:\Users\Mahlu\Desktop\example2\node_modules\async\lib\async.js:167:37

**Comment by jeanmatthieud** [comment]
Could you add your code ?

**Comment by bradvogel** [comment]
Also having trouble:

```
require('request')({
      method: 'GET',
      url: 'https://mixmax.com/images/logo_mixmax_2x.png',
      encoding: null
    }, function(err, res) {
      var color = ColorThief.getColor(res.body);
      console.log('color', color)
    });
```

**Comment by jovrtn** [comment]
It appears that the docs fail to mention that the getColor() and getPalette() methods expect the sourceImage to be an image already processed by Jimp and **_not**_ just the raw binary image data you'd get from the request module like in @bradvogel's example.

I was able to get it working this way:

```
var Jimp = require('jimp');
var ColorThief = require('color-thief-jimp');

Jimp.read(imageUrl, function (err, image) {
     var rgb = ColorThief.getColor(image);
     console.log(rgb); // Works!
});
```

Hope this helps!

**Comment by bradvogel** [comment]
Thanks, but what's an example of `imageUrl`?

**Comment by jovrtn** [comment]
It can be a direct URL to a file. Check out the Jimp documentation for what file inputs are acceptable: https://github.com/oliver-moran/jimp

**Comment by bradvogel** [comment]
Oh, I see now. Mind updating the readme?

**Comment by mrmartineau** [comment]
@bradvogel why don't you submit a PR? 😉

**Comment by bradvogel** [comment]
Updated the example in the readme to be more complete: https://github.com/jeanmatthieud/color-thief-jimp/pull/2
